### ISSUE TITLE
Unknown port mapping for service

### ISSUE THREAD

**Issue by alexbourne** [fabianoo/spring-localstack#13]
Hi, I've looked at similar issues etc., and maybe my code isn't set up right, but after many different attempts I still cannot get this to work.

I have followed the example on the readme (added the library to my pom and spring.localstack.enabled=true) but whenever I run my test I get the "Unknown port mapping for service" error which from code appears to be trying to find a file somewhere under /opt/code/localstack/. I'm running on OSX and this folder does not exist, even if I have installed localstack on the machine using pip.  Please explain how this will ever work.

My test looks like this:

`
@SpringBootTest
class ComSpreadsheetRetrieverTest {

    @Autowired
    private AmazonS3 amazonS3;

    @Autowired
    private ComSpreadsheetRetriever comSpreadsheetRetriever;

    @BeforeEach
    void setUp() {
        amazonS3.createBucket("comSpreadsheets");
        File spreadsheet = new File("src/test/resources/single_item_com_day_report.xlsx");
        amazonS3.putObject("comSpreadsheets", spreadsheet.getName(), spreadsheet);
    }

    @Test
    void canRetrieveSpreadsheetFromS3() {
        File file = comSpreadsheetRetriever.getSpreadsheetFile();
        assertTrue(file.exists());
        assertEquals("single_item_com_day_report.xlsx", file.getName());
    }

    @TestConfiguration
    public static class Sq3TestConfiguration {
        @Bean
        public LocalstackDocker localstackDocker() {
            return LocalstackDocker.getLocalstackDocker();
        }

        @Bean
        public AmazonDockerClientsHolder amazonDockerClientsHolder(LocalstackDocker localstackDocker) {
            return new AmazonDockerClientsHolder(localstackDocker);
        }
    }
`

**Comment by alexbourne** [comment]
I found the solution to this eventually myself - using these application property settings:

spring.localstack.enabled=true
spring.localstack.services=s3
spring.localstack.version=0.9.1

After some debugging I found that the command looking for this path "/opt/code/localstack/.venv/lib/python2.7/site-packages/localstack_client/config.py" runs inside the container, so reverting to an earlier container was the solution using the above settings.

**Comment by soelvar** [comment]
Great.... Sorry not to be more helpful, but I am on vacation atm.

Cheers,
Jesper

**Comment by mtalhajamil** [comment]
Still facing this issue on windows.


```
@RunWith(SpringLocalstackDockerRunner.class)
@SpringLocalstackProperties(services = { LocalstackService.SQS})
@ContextConfiguration(classes = SpringTestContext.class)
@AutoConfigureMockMvc
@ActiveProfiles("test")
public class ListnerTest {


    @Value("${monetization.booking,event.queue}")
    private String monetizationBookingEventQueue;

    @Autowired
    AmazonSQS amazonSQS;
 @Test
    public void basicTest() throws InterruptedException {
        //AmazonSQS amazonSQS = DockerTestUtils.getClientSQS();
        //amazonSQS.createQueue(monetizationBookingEventQueue);
        String queueUrl = amazonSQS.createQueue(monetizationBookingEventQueue).getQueueUrl();
        amazonSQS.sendMessage(queueUrl, "salam");
        Thread.sleep(1000);
        System.out.println("GOT MESSAGE: " + amazonSQS.receiveMessage(queueUrl).getMessages());
    }
}
```
